[package]
name = "rust-os"
version = "0.1.0"
authors = ["skim"]
edition = "2018"

[dependencies]
bootloader = "0.8.9"
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
